name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - conda
  - python=3.7
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda
  - anaconda-navigator
  - navigator-updater
  - pytorch
  - torchvision
  - cudatoolkit=10.2
  - pillow
  - pipreqs
